#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# MIT © Sindre Sorhus - sindresorhus.com
# https://gist.github.com/sindresorhus/7996717

# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

echo "Git post-checkout."
check_run package.json "npm install"
