name: Code Quality

on: push

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run: npm install
    - run: npm run eslint
    - run: npm run stylelint
    - run: npm run prettier:check
    - run: npm run build
