name: Deployment

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Integration Tests (Cypress)
        env:
          CYPRESS_BASE_URL: https://yuliya-zhukova.github.io/leben-in-deutschland
        run: npm run cy:ci
